# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a18d6c7b4b4398d5ebee3c811389fd4468b014e16400839a87a0a1ff359aa0e48889cdb8de1c551f8f0d03370f7d740d0a95d7b96246c3dc330c4ef024b8ddd

test:
  secret_key_base: d68635e4fba3d5fc7cfb79ed980e256e65fb80ae71023d39c70f29aa9285a17ac04e27b4b208be45fa1233543d539daab489eb2527ed7b711393e62a8d430514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
